test:
  adapter: postgresql
  database: cucumber_app_test
  username: root
  password: root
  host: localhost
  port: 5432
  pool:
  reaping_frequency:
  dead_connection_timeout:
  timeout: 5000
  encoding: utf8


development:
  adapter: postgresql
  database: cucumber_app
  username: root
  password: root
  host: localhost
  port: 5432
  pool:
  reaping_frequency:
  dead_connection_timeout:
  timeout: 5000
  encoding: utf8


